# -*- coding: utf-8 -*-
"""python code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BaWPDwFTWE3NxdPquLbqgYUM3mvXbIJx
"""

custo_unitario = 20.00
despesas_gerais = 1000.00
vendas_previstas = 60
margem_lucro = 0.10


quantidade_real_vendida = int(input("Digite a quantidade real vendida: "))
preco_unitario_venda = float(input("Digite o preço unitário de venda: R$ "))


receita_total = quantidade_real_vendida * preco_unitario_venda
custo_total = (quantidade_real_vendida * custo_unitario) + despesas_gerais
lucro_bruto = receita_total - custo_total


lucro_liquido = lucro_bruto * (1 + margem_lucro)


print("\nResultados do Cálculo de Lucro")
print(f"Receita Total: R$ {receita_total:.2f}")
print(f"Custo Total: R$ {custo_total:.2f}")
print(f"Lucro Bruto: R$ {lucro_bruto:.2f}")
print(f"Lucro Líquido (considerando a margem de lucro de {margem_lucro*100}%): R$ {lucro_liquido:.2f}")